name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up jdk 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: grant execute permission for gradlew
        run: chmod +x gradlew
      - name: start sut
        # запускаем sut,
        # имя файла sut будет отличаться в каждой задаче.
        # & означает, что в фоновом режиме не блокируем терминал для запуска тестов,
        # обязательно должен быть для запуска sut в ci
        run: java -jar ./artifacts/app-order.jar &
      - name: build with gradle
        # запускаем автотесты
        # для проектов на базе selenide необходимо добавить параметр для запуска браузера
        # в headless режиме -dselenide.headless=true, параметр --info должен остаться
        run: ./gradlew test --info